### ISSUE TITLE
Runtime Error - Fonts Asimov!

### ISSUE THREAD

**Issue by zotherstupidguy** [shawn42/omg_aliens#1]
```
bundle exec ruby /home/zotherstupidguy/repocode/gamebox_shit/omg_aliens/config/../src/app.rb
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/actor_factory.rb:42:in `rescue in block in build':  (RuntimeError)
          score not found: 
          #<RuntimeError: Could not open TTF file /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/data/fontsAsimov.ttf>
          /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/font_style.rb:16:in `text_width'
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/font_style.rb:16:in `calc_width'
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/actors/label.rb:44:in `recalculate_size'
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/actors/label.rb:32:in `block (4 levels) in <top (required)>'
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/publisher-1.1.2/lib/publisher.rb:83:in `call'
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/publisher-1.1.2/lib/publisher.rb:83:in `block in fire'
/home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/publisher-1.1.2/lib/publisher.rb:79:in `each'

    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/actor_factory.rb:14:in `block in build'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/conject-0.1.8/lib/conject/object_context.rb:66:in `in_subcontext'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/actor_factory.rb:13:in `build'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/stage.rb:23:in `create_actor'
    from /home/zotherstupidguy/repocode/gamebox_shit/omg_aliens/src/demo_stage.rb:13:in `block (2 levels) in <top (required)>'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/stage_manager.rb:81:in `activate_new_stage'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/stage_manager.rb:59:in `switch_to_stage'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/core/game.rb:8:in `configure'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/gamebox_application.rb:29:in `setup'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/gamebox_application.rb:22:in `start'
    from /home/zotherstupidguy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gamebox-0.5.5/lib/gamebox/gamebox_application.rb:14:in `run'
    from /home/zotherstupidguy/repocode/gamebox_shit/omg_aliens/config/../src/app.rb:7:in `<main>'
rake aborted!
Command failed with status (1): [bundle exec ruby /home/zotherstupidguy/rep...]

Tasks: TOP => default => run
(See full trace by running task with --trace)
```

**Comment by shawn42** [comment]
@zotherstupidguy Thanks for the bug report.

I'm trying to reproduce this locally, but it's working for me. What OS and version of Gosu are you using?

**Comment by zotherstupidguy** [comment]
Hi @shawn42 I'm using ubuntu distro with bundler which is using   `gem "gamebox", '~> 0.5.0'` from the provided Gemfile

**Comment by zotherstupidguy** [comment]
Actually I gave it another try, as I wasn't 100% sure. and instead I had to install `sudo apt-get install libxml2-dev` to do a bundle install. and after that I did `bundle exec ruby src/app.rb` and I got a blank black screen with a cursor! nothing happening! any idea?

**Comment by zotherstupidguy** [comment]
![omg_aliens](https://cloud.githubusercontent.com/assets/10923261/7347847/1bcb5532-ecf5-11e4-9aad-4f7bd42caa19.png)

**Comment by shawn42** [comment]
The current Gemfile has 0.4.0 specified. That's not a big deal, but it makes me wonder where you got the Gemfile you have. (Are you looking at your Gemfile.lck?)
https://github.com/shawn42/omg_aliens/blob/master/Gemfile#L3

There are linux issues with loading custom fonts in Gosu. (Not if they are fixed, I'll fire up a VM later today). https://github.com/jlnr/gosu/issues/18

I'd confirm that the Gosu examples work to make sure your setup is correct.

**Comment by shawn42** [comment]
That screenshot is what I would expect from a newly generated Gamebox game, not omg_aliens.

Can you check your repo url in your .git/config?

**Comment by zotherstupidguy** [comment]
actually yes, again as i was hacking carelessly trying to have fun with gamebox, i thought that gamebox gem have omg_aliens installed as a sample, as a bit misleading info on the gamebox site or somewhere gave instructions to create `gamebox n omg_aliens` or somthing simliar.

Now I am using the repo, and I am getting the error again!

**Comment by zotherstupidguy** [comment]
![omg_aliens](https://cloud.githubusercontent.com/assets/10923261/7347979/4b1dbef0-ecf6-11e4-9b30-4c4b4a683bc3.png)

**Comment by shawn42** [comment]
Looks like the font paths were wrong in the config/environment.rb file. Please pull and let me know if that fixes the issue.

**Comment by zotherstupidguy** [comment]
Success!!!! Thank you, you are AWESOME =) 

![omg_aliens](https://cloud.githubusercontent.com/assets/10923261/7349824/6e2a45f4-ed04-11e4-9cfa-0d026d4ce1f6.png)

**Comment by shawn42** [comment]
Awesome. I haven't updated this in a while, but I noticed with newer versions of Gosu / Ruby, the hitboxes are wrong. I will have to look into that more another time.  The most up to date Gamebox example is https://github.com/shawn42/killbox   

Let me know if you have anymore troubles.

**Comment by zotherstupidguy** [comment]
Great! Thanks again, and yeah it looks like you need a helping hand with this, I noticed the tutorials lacking... if you would like to assign something to me I will be happy to give it a try =)

**Comment by shawn42** [comment]
Gamebox sure could use some more tutorials. Feel free to write something up, or just make a game with Gamebox and document what you did.  ;)
